
INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    'aespa 공식응원봉',
    39000,
    'goods',
    'https://image.yes24.com/goods/110367601/XL',
    9,
    TO_DATE('2023-12-01', 'YYYY-MM-DD'),
    130,
    10,
    'https://image.yes24.com/goods/110367601/XL',
    null,
    'aespa',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '레드벨벳 (Red Velvet) 3집 - Chill Kill',
    59400,
    'goods',
    'https://image.yes24.com/goods/123023958/XL',
    9,
    TO_DATE('2023-11-13', 'YYYY-MM-DD'),
    130,
    10,
    'https://image.yes24.com/goods/123023958/XL',
    null,
    '레드벨벳',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '태연 (TAEYEON) - 미니앨범 5집 : To. X [A Ver.]',
    18600,
    'goods',
    'https://image.yes24.com/goods/123374159/XL',
    9,
    TO_DATE('2023-11-27', 'YYYY-MM-DD'),
    130,
    10,
    'https://image.yes24.com/goods/123374159/XL',
    null,
    '태연',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '(PLVE ver.) IVE THE 1st EP I’VE MINE',
    12600,
    'goods',
    'https://cdn5-aka.makeshop.co.kr/shopimages/starshipes/0030130005092.jpg?1696913988',
    9,
    TO_DATE('2023-11-27', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn5-aka.makeshop.co.kr/shopimages/starshipes/0030130005092.jpg?1696913988',
    null,
    '아이브',
    30,
    'null',
    null,
    30
);

INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '[임영웅 공식MD] IMHERO TOUR 2023 MD',
    11000,
    'goods',
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6343172145/B.jpg?970000000',
    9,
    TO_DATE('2023-11-11', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6343172145/B.jpg?970000000',
    null,
    '임영웅',
    30,
    'null',
    null,
    30
);

INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '[임영웅 공식MD] 공식응원봉',
    45000,
    'goods',
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6452695037/B.jpg?112000000',
    9,
    TO_DATE('2023-11-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6452695037/B.jpg?112000000',
    null,
    '임영웅',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '미니브 키링 스마트톡 MINIVE 굿즈',
    9900,
    'goods',
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6199646712/B.jpg?270000000',
    9,
    TO_DATE('2023-11-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6199646712/B.jpg?270000000',
    null,
    '아이브',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '[특전] 에스파 (aespa) - 2024 SEASONS GREETINGS 시즌그리팅',
    50000,
    'goods',
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6411095856/B.jpg?406000000',
    9,
    TO_DATE('2023-11-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/6411095856/B.jpg?406000000',
    null,
    '에스파',
    30,
    'null',
    null,
    30
);

INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '에스파 후드티',
    69000,
    'goods',
    'https://media.bunjang.co.kr/product/238375776_2_1698470337_w360.jpg',
    9,
    TO_DATE('2023-11-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://media.bunjang.co.kr/product/238375776_2_1698470337_w360.jpg',
    null,
    '에스파',
    30,
    'null',
    null,
    30
);

INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '아이유 후드티',
    69000,
    'goods',
    'https://media.bunjang.co.kr/product/228182083_1_1691450807_w%7Bres%7D.jpg',
    9,
    TO_DATE('2023-09-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://media.bunjang.co.kr/product/228182083_1_1691450807_w%7Bres%7D.jpg',
    null,
    '아이유',
    30,
    'null',
    null,
    30
);


INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    '아이유 콘서트 볼캡',
    69000,
    'goods',
    'https://media.bunjang.co.kr/product/236331201_1_1695786420_w%7Bres%7D.jpg',
    9,
    TO_DATE('2023-09-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://media.bunjang.co.kr/product/236331201_1_1695786420_w%7Bres%7D.jpg',
    null,
    '아이유',
    30,
    'null',
    null,
    30
);

INSERT INTO product (
    product_No,
    product_category_id,
    product_Name,
    product_Price,
    dtype,
    product_Content,
    product_Star,
    product_Date,
    read_Count,
    product_Stock,
    product_Image,
    product_Movie,
    product_Artist,
    period_of_use,
    product_Address,
    vote_id,
    product_qty
)
VALUES (
    product_product_no_seq.nextval,
    2,
    'BLACKPINK CD PLAYER',
    149000,
    'goods',
    'https://cdn-contents.weverseshop.io/public/shop/c89408018c8ee0b81a318ad1c8489d61.png',
    9,
    TO_DATE('2023-09-17', 'YYYY-MM-DD'),
    130,
    10,
    'https://cdn-contents.weverseshop.io/public/shop/c89408018c8ee0b81a318ad1c8489d61.png',
    null,
    '블랙핑크',
    30,
    'null',
    null,
    30
);
 commit;