INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (1, s, 1);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, s, 10);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-24', 20);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, sysdate, 30);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-25', 40);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-26', 50);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-27', 60);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-28', 70);
INSERT INTO vote (vote_id, vote_date, vote_tot) VALUES (vote_no_seq.NEXTVAL, '2023-10-29', 80);
